version: "3.9"

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./wordpress:/var/www/html:delegated
  mariadb:
    container_name: mariadb
    image: mariadb:10.6.11
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: secret
  wordpress:
    container_name: wordpress
    image: wordpress:php8.1-fpm-alpine
    volumes:
      - ./wordpress:/var/www/html:delegated
    environment:  
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress
  