version: "3.9"

networks:
  wordpress:

volumes:
  wordpress:

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 8080:80
      - 8081:443
    volumes:
      - /wordpress/:/var/www/html:delegated
    depends_on:
      - wordpress
      - mariadb
    networks:
      - wordpress

  mariadb:
    container_name: mariadb
    image: mariadb:10.6.11
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: secret
    networks:
      - wordpress
    volumes:
      - /mariadb/:/var/lib/mysql
    
  wordpress:
    container_name: wordpress
    image: wordpress:php8.1-fpm-alpine
    volumes:
      - /wordpress/:/var/www/html
    environment:  
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress

  wp-cli:
    container_name: wp-cli
    build:
      context: .
      dockerfile: wp-cli.dockerfile
    environment:  
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress
    volumes: 
      - /wordpress:/var/www/html:delegated
    networks:
      - wordpress
    depends_on:
      - mariadb
      - wordpress